### ISSUE TITLE
Max height crops out last line of text

### ISSUE THREAD

**Issue by fknussel** [jedfoster/Readmore.js#100]
Hi! I'm getting a fixed height value added to my text that crops out part of it:

![image](https://cloud.githubusercontent.com/assets/1261453/7220772/28653d04-e6aa-11e4-9185-4a848693233b.png)

Although it's possible to cancel out this fixed height programmatically using JS, I don't think that's a good way out. Is there any good reason for the script to be doing this? I don't know whether this is an expected behavior or sth that shouldn't be happening at all.

Thanks in advance!

**Comment by jedfoster** [comment]
Somehow the expanded height isn't being calculated properly. Not sure what to tell you about that. 

The fixed height is necessary for the expand/collapse animation. `height: auto` can't be used in CSS transitions. That animation is aesthetically important to me—the entire reason I wrote this—but if you can live without it, #36 might be helpful.
