### ISSUE TITLE
Doesn't add "Read more"

### ISSUE THREAD

**Issue by Robouste** [jedfoster/Readmore.js#102]
Hi, 

I've try using your library but I can't get it work.
```javascript
<script>
    $(document).ready(function () {
        $(".flashProjet").readmore();
    });
</script>
```
This is my code. In page inspector, I see the library added some code like : 

```javascript
<style type="text/css">
 .flashProjet + [data-readmore-toggle], .flashProjet[data-readmore]{display: block; width: 100%;}.flashProjet[data-readmore]{transition: height 100ms;overflow: hidden;}
</style>
```
It also add ' style="max-height: none;" ' to the div.

But there isn't any "read more" anchor to expend the text. 

I tried to define "moreLink" in option but still get nothing.

What am I doing wrong ?

**Comment by imju** [comment]
In my experience, the html tag has to be used instead of css class, which fixed this problem.  It would be something like <flashProject></flashProject> not <p class="flashProject"> </p>

**Comment by EnMod** [comment]
That doesn't seem to be the solution though, since Jed's site itself uses $('#info').readmore();.  Something else must be the case here.

**Comment by mgrimard** [comment]
I'm experiencing a similar issue, though every couple of hard refreshes (maybe 1 in 50) will display the readmore properly minimized.

Otherwise it shows the entire block with max-height: none; and no 'read more' link.

**Comment by jedfoster** [comment]
@Robouste I'd have to see your page or an example on CodePen or jsbin. 

@imju and @EnMod, the actual selector is irrelevant, class name or tag name, doesn't matter; if it can be selected by jQuery, it will work.

@mgrimard As I stated in #84 and elsewhere, Readmore.js won't work on elements that are either hidden or have `height: 0;`. Applying Readmore.js to such elements is currently (and for the foreseeable future) simply impossible.
