### ISSUE TITLE
Toggle readmore by exist button

### ISSUE THREAD

**Issue by vinhtq** [jedfoster/Readmore.js#108]
Could i toggle readmore by using exist button?

For example:
I have button somewhere on the page, when i click it will toggle the readmore text on somewhere else of the page?

**Comment by cgwic** [comment]
@vinhtq example from the [main page](http://jedfoster.com/Readmore.js/)

## Toggling blocks programmatically:
You can toggle a block from code:

```
$('article:nth-of-type(3)').readmore('toggle');
```

**Comment by vinhtq** [comment]
It will not work because the article needs to initialise before anything can trigger it.
The example you give me is the button including in the text not outside!

I think in the option you can make new one something like: triggerClass or triggerButton with allowing jquery or dom as parameter:

triggerClass: ".myButton"

**Comment by cgwic** [comment]
@vinhtq Sure article needs to be initialized first.
But you can use toggle from outside of text.
If i got you right [here](http://jsbin.com/luqozumaqa/edit?html,output) simple example

**Comment by jedfoster** [comment]
@vinhtq, @cgwic's answer is correct.
