### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by YLYS** [jedfoster/Readmore.js#11]
Hello,
I try to apply readmore in drupal installation, and when I test script in my chrome console I get this error:
TypeError: undefined is not a function
Would you help me please ? Thank you.

**Comment by mikkeljohnsen** [comment]
I get the same error.

** Message: console message: readmore.min.js @11: TypeError: undefined 
is not a function (evaluating 'e(d).on("click",function(e){t.toggle(this,n[0],e)})')

**Comment by mutantturkey** [comment]
I'm getting the same thing here
