### ISSUE TITLE
Only works on first element when applied to an element inside bootstrap 3 carousel.

### ISSUE THREAD

**Issue by quexal** [jedfoster/Readmore.js#111]
Hello,
I've got a bootstrap carousel with readmore applied to a div containing text inside the carousel body.

Readmore only seems to run on the 1st slide in the carousel.

Example:
HTML
```html
<div id="carousel-test" class="carousel slide" data-ride="carousel">
    <div class="item active">
        <div class="carousel-inner" role="listbox">
            <div class="carousel-container">
                <p class="text readmore-text">blah blah blah blah...insert lots of text here</p>
           </div>
       </div>
    </div>
   <div class="item">
        <div class="carousel-inner" role="listbox">
            <div class="carousel-container">
                <p class="text readmore-text">blah blah blah blah... insert lots of text here.</p>
           </div>
       </div>
    </div>
</div>
```

JS:
`
 $(document).ready(function() {   
           $('.readmore-text').readmore();
 });
`

The above (when you add enough text for readmore to take effect) results in readmore only being applied to the `<p>` element in the first slide item, and not any subsequent slides.
 

Edit:  It does however insert `style="max-height: none;"` on the subsequent elements.

**Comment by jedfoster** [comment]
My guess is that the carousel is hiding the other slides. Readmore calculates heights, and in order to do that, the element needs to be visible.

**Comment by quexal** [comment]
Yep.. looks about right… have switched to jQuery Expander instead (https://github.com/kswedberg/jquery-expander)
