### ISSUE TITLE
Unable to get readmore.js to work on our website

### ISSUE THREAD

**Issue by redbrad0** [jedfoster/Readmore.js#114]
If you go to http://www.pegstar.net/ and view the source you will see the large amount of text in the middle of the site is all inside 'article' tags. I have included http://www.pegstar.net/wp-content/themes/pegstar/js-readmore/readmore.js into the header and have tried a couple items from the sample code but none of it will minimize the text shown. Am I doing something incorrectly or will it not work on the layout we have on this website?

Here is a few things I have tried
<script>
$('article').readmore();
</script>

<script>
$('article').readmore({speed: 500});
</script>

<script>
$('article').readmore({
  speed: 75,
  lessLink: '<a href="#">Read less</a>'
});
</script>

**Comment by jedfoster** [comment]
You need to actually invoke Readmore on the elements you want collapse, https://github.com/jedfoster/Readmore.js#use

**Comment by redbrad0** [comment]
I was able to get this fixed last night. I forgot exactly what I did but I want to say I moved the part where I invoke the readmore.js to the bottom of the page and it started to work.
