### ISSUE TITLE
beforeToggle loading ajax content

### ISSUE THREAD

**Issue by kubante** [jedfoster/Readmore.js#117]
Hi!, thanks for this very neat plugin. 

I noticed an issue though: you made an example with ajax loaded content, but the content is loaded first and then the readmores are called upon that loaded content. 

What if the content would need to be triggered AFTER having clicked on the readmore? at the moment the beforeToggle permits to do that, the content is loaded in succesfully, but the readmore then only expands to a certain point, not to the end of the freshly loaded content. Do you know what I mean?  Any Ideas how I could accomplish this in a not too hacky way?  

I was planning to create a button that loads the content first, and then manually trigger your readmore on that div, but it kind of doesnt look very neat, especially coz i wanna avoid having 2 buttons. 

Maybe you can point me in the right direction .. 

Thanks ahead, 

Jacob

**Comment by jedfoster** [comment]
There's no way to calculate the expanded height of content that doesn't (yet) exist. Readmore.js can only operate on the current DOM.
