### ISSUE TITLE
Display "read more" on the same line as the text to expand/collapse

### ISSUE THREAD

**Issue by hfirdaus** [jedfoster/Readmore.js#120]
Hi,

I love the Readmore.js and am using it for Drupal. I wanted to get my expandable text showing up like this:

Some info some info some info some info some info some info some info some info some info some info some info some info some info some info some info some info some info some info some info some info some info ...read more

To do this, using CSS, I changed settings to "display:inline", which gets it to show up like above, however, then the actual functionality is lost, and clicking "read more" does absolutely nothing. I am aware that the settings of the Readmore.js require it to be display:block, hence I was wondering if anyone figured out another way to do this? I would much appreciate it.

**Comment by jedfoster** [comment]
Readmore was specifically _not_ designed to do this. There are numerous other plugins that will accomplish this functionality.

**Comment by NJichev** [comment]
This should help http://stackoverflow.com/questions/35640419/readmore-js-put-readmore-link-inside-div-not-below
