### ISSUE TITLE
How would you handle a window resize event properly?

### ISSUE THREAD

**Issue by Amaranthos** [jedfoster/Readmore.js#124]
When resizing the window Readmore doesn't automatically recalculate the appropriate height and cutoff for the element. Is there an appropriate way to do so?

**Comment by jedfoster** [comment]
What version are you using? Readmore.js already attaches an event handler for the `resize` event on `window`, so it should already be recalculating expanded/collapsed heights.

**Comment by Amaranthos** [comment]
I am using v2.1.0,  currently if I resize the the browser using Windos Key + Left or Right (Google Chrome, Windows 10) a large chunk of blank space is added to the divs, I believe this is because it isn't being updated. Works fine if the page is refreshed while at the smaller size, just not when resizing between maximised and docked to the edge of a screen.

**Comment by Amaranthos** [comment]
Also I am using it in conjuction with Masonry to achieve a staggered column layout, if that is helpful. You can see the site [here](http://joshuas.software/)

**Comment by Sammael1106** [comment]
Hi! I'm using readmore.js 2.0.4 on the hidden element. And it's okay, when I showing the element - readmore.js works perfectly and my element collapses to normal height. (For example: style="max-height: none; height: 541px;")

But If I resized the window before showing the element - element collapses to zero height (style="max-height: none; height: 0px;")
