### ISSUE TITLE
It is not working for data that is dynamically loaded through Ajax

### ISSUE THREAD

**Issue by sraminen** [jedfoster/Readmore.js#125]
How should i use the plugin for data that is dynamically loaded through ajax. Currently i am calling  $('article').readmore() function whenever the data is loaded through ajax, but this is removing the readmore functionality on other elements that are already loaded. Please help

**Comment by jedfoster** [comment]
Depends on how you are loading that new content. I'd have to see your code. Please post your code or a link to your page.

**Comment by ParallelUniv3rse** [comment]
Just stumbled upon the same issue, in the destroy method calling `current.removeData('plugin_' + readmore);` instead of `current.removeData();` fixes this issue. 
Else somehow the plugin just gives up on reinitializing the elements with readmore data already on them.
