### ISSUE TITLE
Not works for DIVs which are initially invisible 

### ISSUE THREAD

**Issue by samsonbek** [jedfoster/Readmore.js#128]
If my div has style "display: none" when page loads, readmore() not works for this div.
Here is the example:
http://jsfiddle.net/samsonbek/hubusf30/

**Comment by davidpelayo** [comment]
I'm having the same issue. 

Essentially, the HTML structure I'm having is similar to a bootstrap `nav-bar` concept, where a list of links points to different containers.

On those containers, I need to initialise the read-more for long contents rendition.

How did I solve it so far? Initially I'm initialising all read-mores on the DOM, and then on each new selected tab as active event, I need to destroy the instances and rebuild them again.

Probably, a better approach to solve this issue would be to initialise only the ones that are visible (current active tab). But what if I can't predict which element will be visible on the screen?

**Comment by huwrowlands** [comment]
Got the same issue here with jQuery tabs. Only works on the first visible tab.

**Comment by davidpelayo** [comment]
With the latest [npm package released](https://www.npmjs.com/package/readmore-js) is working for me.

**Comment by zuhloobie** [comment]
Not using NPM, just calling the JS from <head> - is there a fix for this? It collapses content on the other tabs just fine, but the read more/close functionality (links) aren't visible so there isn't a way to expand. Thanks in advance...

**Comment by zuhloobie** [comment]
I got this to work by initializing Readmore on the index page (as you normally would). Then on my JS code for showing/hiding tabs, I destroy Readmore and start it again (after the new tab content is shown). Probably hack-ish, but works LOL.

**Comment by paulcripps** [comment]
If you are using bootstrap something like this works:

    $('.collapse').on('shown.bs.collapse', function(){
        // start read moe again
    });

**Comment by jedfoster** [comment]
I would recommend doing what @zuhloobie is doing.

If the content is hidden at the time Readmore.js is invoked, it won't be able to properly calculate heights. 

To expand on @paulcripps' suggestion, something like this should work:

```javascript
$('.your-selector').readmore({/* your configs */});

$('.collapse').on('shown.bs.collapse', function() {
    $('.your-selector').readmore({/* your configs */});
});
```

Or, perhaps even this: 

```javascript
$('.your-selector').readmore({/* your configs */});

$('.collapse').on('shown.bs.collapse', function(event) {
    // Limit the elements on which Readmore.js is init'd to the current tab panel
    $(event.target).find('.your-selector').readmore({/* your configs */});
});
```

YMMV. If you get a working solution, please post it here.
