### ISSUE TITLE
Very Slow Load Time

### ISSUE THREAD

**Issue by yaniv691** [jedfoster/Readmore.js#130]
Hi,

I use Readmore.js on a very long web page with a lot of elements that use the plugin. I think it's a great plugin! Due to the size of the page it takes ~5 seconds to load because of readmore.js doing its magic in the background.

Is there any way to make it load faster?

Thanks!

**Comment by jedfoster** [comment]
Can you either post a link to your page or [fork this bin](http://jsbin.com/mokove/edit?html,css,js,output) and replicate your issue?

**Comment by yaniv691** [comment]
@jedfoster Here's the page: https://www.ravellosystems.com/ravello-api-doc/
