### ISSUE TITLE
Toggle not working

### ISSUE THREAD

**Issue by adrianwhyte** [jedfoster/Readmore.js#131]
I found that the toggle function wasn't working. If I replaced "_this" with "this" on lines 227 and 231 this seemed to fix it.

**Comment by maxbeizer** [comment]
@jedfoster I created this [JSFiddle](https://jsfiddle.net/ax8cz6yy/14/) to reproduce the issue. @adrianwhyte thanks for reporting this with a work around.

**Comment by PVGrad** [comment]
This bug is still in last 2.1.0 version. Why don't you merge the fix from pull request #137 ? Thanks
