### ISSUE TITLE
Read More and Angular Linking

### ISSUE THREAD

**Issue by naveen305** [jedfoster/Readmore.js#133]
Hello,

We created readmore js with angular directive, when page goes to partial view readmore js is not defined  please find the image !
![readmore](https://cloud.githubusercontent.com/assets/12660060/11393369/5bb52150-9385-11e5-8870-a594e00da073.jpg)

**Comment by jedfoster** [comment]
I would need to see your directive and perhaps even a demo of the issue. You have given me nothing to go on.
