### ISSUE TITLE
$.readmore({embedCss:false}) is meaby not working properly 

### ISSUE THREAD

**Issue by djalfe** [jedfoster/Readmore.js#134]
Hey there
had some trouble removing the < style >< /style >, .readmore() is making in < head >.

The way i did it, was putting a if statement around embedCSS(this.options);
https://github.com/jedfoster/Readmore.js/blob/master/readmore.js#L154

if (this.options.embedCSS) {
        embedCSS(this.options);
}

Is there another way todo it or ???

**Comment by jedfoster** [comment]
Can you please describe the problem you are trying to solve?
