### ISSUE TITLE
Some way of knowing when the Read More wasn't necessary?

### ISSUE THREAD

**Issue by dnchristiansen** [jedfoster/Readmore.js#136]
I have some functionality that I want to happen only once a user has seen the full text. The `afterToggle` callback works great for text that is clipped. However, sometimes the text isn't long enough to need the Read More link, so the they see the full text right away. Is there any property or callback that could be used to know that the Read More link wasn't needed?

**Comment by dnchristiansen** [comment]
In looking at the code, just calling a callback on line 190 (https://github.com/jedfoster/Readmore.js/blob/master/readmore.js#L190) seems like it would be perfect for this.

**Comment by jedfoster** [comment]
Added `blockProcessed` callback. Use like so:

```javascript
$('article').readmore({
  blockProcessed: function(element, collapsable) {
    if(!collapsable) {
      console.log('This element was too short for Readmore: ', element);
    }
  }
});

```
