### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sjf43** [jedfoster/Readmore.js#138]
Is it possible to install readmore without using npm.  I am a newbie and have never used npm.
SJF43

**Comment by jedfoster** [comment]
```
$ bower install readmore-js
```

But you'll need npm to install Bower, if you don't already have it. (I know, it's very chicken-and-egg, but welcome to modern web development.)

You'll find that most JavaScript libraries are installable with npm these days; I would strongly encourage you to learn you some npms. Here are a few good links to get you started:

https://gist.github.com/chrisbuttery/f3a75478fa81950df39f (This one's a link to other links, good round up of resources.)
http://www.sitepoint.com/beginners-guide-node-package-manager/
http://www.anotheruiguy.com/ux-design-dev/_book/node-workshop/node-npm.html
http://smalljs.org/package-managers/npm/

---

Alternatively, you can clone this repo and copy the files over to your project—but that's so 2008!

**Comment by sjf43** [comment]
Thank you for taking the time to respond and for the links.I guess I need to start learning.Sean
