### ISSUE TITLE
Chrome: readmore.js does not collapse when page is zoomed out

### ISSUE THREAD

**Issue by romancieslik** [jedfoster/Readmore.js#139]
On Chrome, readmore.js stumbles over a zoomed-out page when the collapsed text is rather short (just over the limit). I guess that after zooming out the collapsed text is measured to be shorter than it is. 

Steps to reproduce:
1. Go to http://www.gut-fuer-hamburg.de/
2. Scroll down to "Neuigkeiten"
3. Zoom out the Page to 75% with CMD-Minus
4. Press "Mehr"

Affected browsers: Chrome 47 on OSX.
Not affected browsers: Firefox & Safari on OSX.

Tried to reproduce it on jsfiddle, but zooming out reveals not this bug but another unwanted behavior here: http://jsfiddle.net/jscou0nh/3/

**Comment by jedfoster** [comment]
At 75%, the `height()` of that element is 231px—greater than the `collapsedHeight` of 230px—but at any other scale it is 230px. That 1px causes it to fail the `$element.height() <= collapsedHeight` conditional and fall into the collapsed state, the state it's already in.

My best guess at a possible cause is pixel rounding. Chrome's inspector reports the height as 230px, but jQuery doesn't agree. 

It's either pixel rounding or vampires.

---

Not sure what the best solution would be... I'll try to find a fix on my end, but I don't expect much; you could also tweak the `collapsedHeight` you are configuring.

On the off chance it's vampires, I'd recommend garlic.

**Comment by romancieslik** [comment]
Seems to be fixed, thank you!

**Comment by delwaterman** [comment]
@jedfoster We ran into this issue as well. Any change getting psyipm commit into master?

**Comment by developer-subash** [comment]
I got issue when my browser size is 90 % and here i got a code .

https://github.com/psyipm/Readmore.js/commit/600fbfc96906aae8a9cf5930a8d682d1cecb858a
