### ISSUE TITLE
Any ideas how to include text fading option?

### ISSUE THREAD

**Issue by Heming1way** [jedfoster/Readmore.js#141]
I hope this is the right place to present such an issue.
As far as I'm concerned I find fading text in "Read more ..." situations a very intuitive concept: The optical impression of the fading words stimulates the awareness that the text continues beyond the bottom line and can be made visible by clicking the button, and perhaps even stimulates the user's curiosity to click. Without the fading, quick and superficial visitors might not be attracted to click. That's probably why Amazon applies the option.
Although trying hard, I haven't been able to realize the feature. The css does the fading alright:
`.readmore:before { background:linear-gradient(transparent 150px, white); }`
but it also fades the "Read more ..." button into illegibility (i.e., some bottom margin must be included), and, most important, how can I manage the toggling between faded (cut-off) and solid (expanded) text?
I wonder if my inability is due to my admittedly very modest competence or a question of principle (i.e., cannot be combined, implemented or whatever with Readmore.js). I hope some expert here has a good idea ...
@ jedfoster: I've also sent you an email including link and code but am unsure if it has ever arrived.

**Comment by jedfoster** [comment]
I forked an existing JSBin and cobbled together a solution.

http://jsbin.com/xuciqap/edit?css,js,output

Alex let me know offline that this solution worked for him.

**Comment by christophlieck** [comment]
@jedfoster 

Thanks for the code. I know this is closed, but you should change your line

`background: linear-gradient(rgba(0, 0, 0, 0), rgba(255, 255, 255, 1));`

to 

`background-image: linear-gradient(rgba(255, 255, 255, 0), rgba(255, 255, 255, 1));`

in order to support Safari and allow for more efficient rendering.

**Comment by Heming1way** [comment]
Thanks, Christoph!
I changed my code as you suggested but sorry, couldn't note any difference.
The screenshots show that Chrome and Firefox do the same perfect job as before, while Safari still gives the "last" paragraph a strange grey background ... (Unfortunately I forgot to make the corresponding "before" pics, so you'll have to believe me that they would look exactly the same.)

![chrome 60 0 3112 78 32-bit](https://user-images.githubusercontent.com/17335524/28896059-36f4811c-77db-11e7-9484-ded816fac657.jpg)
![firefox 54 0 1 32-bit](https://user-images.githubusercontent.com/17335524/28896058-36f39946-77db-11e7-9234-4f4b419e172e.jpg)
![safari1](https://user-images.githubusercontent.com/17335524/28896057-36f1c99a-77db-11e7-856c-755db1325f84.jpg)
![safari2](https://user-images.githubusercontent.com/17335524/28896060-36fd0f1c-77db-11e7-948b-9c32e0e3926f.jpg)

**Comment by christophlieck** [comment]
@Heming1way 

sorry to hear this is not working for you. Try to check for caching problems in your local dev environment. The route to go is definitely right. You may want to check online:

http://jsbin.com/zolugupasu/edit?css,js,output

Just replace the line in the bin accordingly and check in Safari. It gives you a nice gradient from transparent to white.

Technical background: Safari behaves according to the specs. So a gradient from "black with zero opacity to black with full opacity" gives a black "image" in the middle of the gradient.
