### ISSUE TITLE
Identify each read more instance uniquely

### ISSUE THREAD

**Issue by webappswiz** [jedfoster/Readmore.js#142]
Is there an option or variable I can use to identify each instance of "read more" uniquely? 
I am trying to track each click on every "read more" on a given page in google tag manager. 
Thanks.

**Comment by jedfoster** [comment]
The toggle elements have an `aria-controls` attribute with a unique value corresponding to the `id` of the block which it toggles. I'm sure you could use that somehow... 

I found [this article](http://www.lunametrics.com/blog/2014/05/08/tracking-clicks-custom-data-attributes-google-tag-manager-google-analytics/) on how to use `data-` attributes to track clicks. The catch is that Readmore.js does not currently expose any identifying values in `data-` attributes. But I will fix that in the next release.

**Comment by jedfoster** [comment]
With the latest change, the toggle elements will have an attribute, `data-readmore-toggle` with the same value as `aria-controls`, the ID of the block it toggles.

Using the Google Tag Manager article above, you would reference the toggle link with something like `gtm.element.dataset.readmoreToggle`, that value should be unique.
