### ISSUE TITLE
Dynamic Height of Readmore Element

### ISSUE THREAD

**Issue by korynorthrop** [jedfoster/Readmore.js#144]
I have a Readmore element in a fluid width container with two sibling elements. The sibling elements and the Readmore element's parent all have equal heights, which are recalculated on resizing the window. I'd like the Readmore element's max-height to change based on the height of its parent (and the parent's siblings). When I try to set the max-height (or the height) of the Readmore element through Javascript it gets replaced by the functions in Readmore.js. Is there a way to accomplish this task? 

Below is a rough depiction of the HTML structure:

```
<div class="panel-grid">
    <div class="panell-grid-cell">
        <article class="readmore-element"></article>
    </div>
    <div class="panell-grid-cell">
    <div class="panell-grid-cell">
</div>
```

So all the `.panel-grid-cell` elements have equal heights on page load and on window resize. I want the `<article>` to be set to the same height as well.

Any help is much appreciated!

**Comment by jedfoster** [comment]
I think this could be achieved if the `collapsedHeight` option could (optionally) be a function. Readmore.js already invokes its `resizeBoxes` function on `window.resize`, so if it could also re-invoke a user-supplied `collapsedHeight` function you'd get the result you're looking for. I think...

I'll see what I can do; it's a reasonable feature.

**Comment by korynorthrop** [comment]
That sounds reasonable to me, thanks for looking into it.

**Comment by felixcheruiyot** [comment]
Hi Guys,

Any update on this?

**Comment by richardskinner** [comment]
Hi People, is this feature available yet?

**Comment by ai-leonid** [comment]
Maybe it will be usefull for somebody:
```JS
function readMoreRecalcHeight() {
    if (typeof(Event) === 'function') {
      // modern browsers
      window.dispatchEvent(new Event('resize'));
    } else {
      // for IE and other old browsers
      // causes deprecation warning on modern browsers
      var evt = window.document.createEvent('UIEvents');
      evt.initUIEvent('resize', true, false, window, 0);
      window.dispatchEvent(evt);
    }
}
```
You can call this function and firing ```resize``` event for recalculating readMore block (firing ```resizeBoxes``` function on ```resize``` event). Can be usefull if you use dynamic content inside readMore and you need recalc height of it. Just call: ```readMoreRecalcHeight()```.
