### ISSUE TITLE
require('readmore-js') fails when used with browserify with error could not find module 'jquery'

### ISSUE THREAD

**Issue by skyzhangty** [jedfoster/Readmore.js#146]
**Problem 1**
having example.js like below
```javascript
global.$ = global.jQuery = require('jquery'); 
require('readmore-js');  
$('.consent').readmore();
```
using browserify
```shell
browserify example.js -o bundle.js
```
and then in the console getting could not find module 'jquery' from readmore calling in jquery.

**Problem 2**
After browserify produced bundle.js, it had jquery 2.1.4 in it together with our version of jquery. The final bundle has 2 jquery libraries if the project using readmore is also specifying jquery. 
Changed the dependencies section in readmore-js package.json and used https://docs.npmjs.com/cli/shrinkwrap to remove the  readmore jquery dependency from the resulting bundle to make sure that was not causing Problem 1 above. 

Used bower to have readmore-js in my project that I am building with npm and browserify to finally get it working. If you are going to drop support for bower it is best to make sure it works with browserify and npm as build tool.
Thanks for the good work, your plugin is helpful.

**Comment by jedfoster** [comment]
I think I figured out what was going here. Let me know if the next version (which I will publish shortly) doesn't work for you.
