### ISSUE TITLE
IE9 and elements created after the DOM loads

### ISSUE THREAD

**Issue by djmtype** [jedfoster/Readmore.js#148]
Basically, I need to append a heading derived from an image alt attribute.

```
$('.child-container img').each(function(i, ele) {
var alt = this.alt;
$(this).closest('.container-parent').append('<h5>'+alt+'</h5>');
});
```

This loads fine on initialization. Once the more/lessLink is clicked I have the `<h5>` translating out of view using `transform: -ms-translateY(-100%); transform: translateY(-100%)`. When the more/lessLink is clicked once again, the `<h5>` should appear back in view, like it does in every browser. Not IE9. 

I've also appended a toggling class name to the parent div when the more/lessLink is clicked.

```
.container-parent {
min-height: 30px;
position: relative;
}

.container-parent h5 {
position: absolute;
left: 0;
top: 0;
width: 100%;
height: 30px;
transform: -ms-translateY(0); 
transform: translateY(0)
}

.container-parent.is-open h5 {
transform: -ms-translateY(-100%); 
transform: translateY(-100%)
}
```

**Comment by jedfoster** [comment]
I'm sorry, I am not supporting IE 9.
