### ISSUE TITLE
Foundation 6 Tabs

### ISSUE THREAD

**Issue by jinch** [jedfoster/Readmore.js#156]
Hi Jed,

Great script / thank you!

Trying to implement this with Foundation 6 (Tabs) but for some reason it only work on the initial active tab and not the others. I suspect its Foundation tab script is interfering with your code.

Do you know of a possible work around to this? It would be great if these could play nice together. I think it may need a function to initiate only after the tab is is triggered but not exactly sure how tto go about that ~ (they changed allot with the latest update).

You can see an example on the layout below.
http://inchdesigns.com/projects/readmore/

**Comment by jedfoster** [comment]
See my comments on these similar issues:

https://github.com/jedfoster/Readmore.js/issues/84#issuecomment-80850641
https://github.com/jedfoster/Readmore.js/issues/102#issuecomment-152794698
https://github.com/jedfoster/Readmore.js/issues/128#issuecomment-218955777

--- 

Depending on exactly how your tabs work, it's likely that the content of background tabs has either `display: none` or `height: 0`, which will prevent Readmore.js from correctly calculating the necessary heights.

**Comment by jinch** [comment]
Thank you / I'll read through and see if I can find a work around.

**Comment by EmWe5** [comment]
I'm experiencing the same problem with Readmore.js inside Foundation 6 Tabs.

@jinch Maybe u were able to figure out a solution?

**Comment by jinch** [comment]
@EmWe5 

Hmmm ~ it's been awhile but I don't think I ever got the readmore.js to play nice with Foundation. If I remember correctly, I just ended up setting up a max-height on the tabs and setting the scroll to auto via CSS to hide the extra content. Sorry, I can't be of more help.
