### ISSUE TITLE
Add release number to comments in src

### ISSUE THREAD

**Issue by maxbeizer** [jedfoster/Readmore.js#163]
Thanks for the lib and all the OSS work ❤️ 

Would it be amenable to add the release version to the comments in the top of the source file? I'm using readmore.js outside of an NPM context and have no idea which version was installed. Something as simple as:

``` js
/*!
 * @preserve
 *
 * Readmore.js jQuery plugin
 * Author: @jed_foster
 * Project home: http://jedfoster.github.io/Readmore.js
 * Version: 2.2.0 <-------------------------------------------- this would really help
 * Licensed under the MIT license
 *
 * Debounce function from http://davidwalsh.name/javascript-debounce-function
 */

```

You could probably build updating the verion into the gulpfile to automate this task on compress.

**Comment by jedfoster** [comment]
Good idea!

**Comment by jedfoster** [comment]
This will be fixed in the next version of Readmore.js.

**Comment by maxbeizer** [comment]
thanks @jedfoster !
