### ISSUE TITLE
aria-expanded value

### ISSUE THREAD

**Issue by berkapavel** [jedfoster/Readmore.js#164]
in safari it has all the time aria-expanded with value false... even if it's opened

<... id="rmjs-1" aria-expanded="false" data-readmore="" style="max-height: none; height: 787px;">

**Comment by karpadiem** [comment]
+1 on this issue.

**Comment by jedfoster** [comment]
Version 3.0 of Readmore.js will drop jQuery entirely, in favor of vanilla JS. I believe this issue will be fixed in the next version.

**Comment by mstrelan** [comment]
Nope, not fixed in 3.0.
