### ISSUE TITLE
outerHeight() is returning an object therefore not working as expected

### ISSUE THREAD

**Issue by teegan-doghouse** [jedfoster/Readmore.js#166]
On Line 82: expandedHeight = el.outerHeight() an object is being returned which is causing readmore not to work. It needs to change to be expandedHeight = el.outerHeight(false) and then it works again.

**Comment by jedfoster** [comment]
What version of jQuery are you using?

**Comment by teegan-doghouse** [comment]
Updated my Jquery UI to 1.10.2 and it works fine now. Realise it is a Jquery UI issue with 1.8
