### ISSUE TITLE
right align read more/read less

### ISSUE THREAD

**Issue by shellwe** [jedfoster/Readmore.js#167]
This isn't an issue, per say, just a question. I just didn't know where to align it. Is there a way build into your program to add a class to the 'a' tag so I can apply CSS to it? I need it right aligned so it stands out more.
Otherwise I will have to play around with adding a class to the a tag with the words 'read more' when it expands or collapses. Just hoping there was a built in way so it would be less messy.

**Comment by shellwe** [comment]
If I could delete this I would. It is obvious now I can customize my read more and read less and just have a class in there. Sorry to bother you.

**Comment by jedfoster** [comment]
np. Glad you figured it out.
