### ISSUE TITLE
afterToggle not working once 'read more' is clicked

### ISSUE THREAD

**Issue by gunnard** [jedfoster/Readmore.js#170]
Hello!
I love the plugin! Working on a situation where once I click read more, clicking 'close' will not trigger anything I have in afterToggle. How can I get a callback to work once I click 'close'

1) I have taken your example from the readmore.js page (about scrolling back up to the top) and verbatim it does not work for me.
2) I AM using this in a wordpress theme, not standalone readmore.js. 
3) Everything works in the afterToggle on the initial 'read more' click. nothing is triggered after the click.

Thank you!
Gunnard Engebreth
Senior Web Developer 
Blend IMC

**Comment by gunnard** [comment]
This is resolved.
I mistakenly believed that I needed my code to run in afterToggle and not beforeToggle. This works fine.

**Comment by jedfoster** [comment]
👍
