### ISSUE TITLE
Expanded height does not resize on iOS in Safari upon orientation rotation

### ISSUE THREAD

**Issue by ewilfong** [jedfoster/Readmore.js#172]
In iOS 9 (maybe others), if you expand the text and then rotate the phone from portrait to landscape mode the height of the element that .readmore function is applied to does not recalculate. This leaves a large gap between that element and the next one.

This appears to be a mobile Safari specific issue as it does not occur in Chrome on iOS nor on Android.

**Comment by sPaCeMoNk3yIam** [comment]
This is an issue on all devices. If you expand a text, resize the window, so the textbox is wider, the height won't change.

**Comment by ewilfong** [comment]
No, that is not true. On all other devices - and in Chrome on iOS - changing the window size causes the expanded text element to resize.

**Comment by ThomasWeiser** [comment]
Same problem here in Chrome 53 on Android 6: No recalculation of the height after orientation change.

**Comment by studentIvan** [comment]
Seems it will never fixed...
