### ISSUE TITLE
Strange height when expanded

### ISSUE THREAD

**Issue by julmot** [jedfoster/Readmore.js#173]
(Screenshots taken from the plugin's website itself)

When collapsed:
![space1](https://cloud.githubusercontent.com/assets/8310677/17832042/48c37cb0-66fa-11e6-8d27-a8816c90c27e.png)

When expanded:
![space](https://cloud.githubusercontent.com/assets/8310677/17832044/4df4727a-66fa-11e6-8fb9-91953761fdf0.png)

The plugin sets a `height` with a strange space. In my case there are 24px additional space between the text and the toggle when expanded.

What's causing this problem?

**Comment by cggit** [comment]
I had this and worked around the bug by switched the containers padding to margin instead.

**Comment by lkraav** [comment]
Confirming the same problem, additional height is being calculated (Firefox 50).

I think I'm going to use one of the callbacks to simply remove the expanded height CSS. Why is it needed anyway? The element usually can have its natural height when expanded.

**Comment by lkraav** [comment]
My solution:

```javascript
afterToggle: function( trigger, element, expanded ) {
    if ( expanded ) {
        element.css( "height", "" );
        element.css( "height", element.height() + "px" );
    }
},
```

First you have to reset the `height` to get normal box height going, then set the correct height to restore the `transition`.

**Comment by 99wesley99** [comment]
One thing I did (on top of the answer above) to get it to animate smoother was to add a <p> tag within my <div> that was calculating height of text. The answer above kind of jolts back to the height but I needed it to be smooth. Don't kill me, i'm newer to posting answers ;)

`afterToggle: function( trigger, element, expanded ) {
    if ( expanded ) {
        var heightOfText = element.find('p').css('height');
        element.css( "height", heightOfText);
    }
}`

**Comment by Anesti22** [comment]
There was still another step for me to fix this.

```
beforeToggle: function( trigger, element, expanded) {
	if ( trigger ) {
		element.toggleClass('hidden');
		element.css( "height", "auto" );
	}
}
```

```
.text-block__content {
	overflow: hidden;
	&.hidden {
		height: auto!important;
	}
}
```

<img width="993" alt="Screen Shot 2021-05-31 at 12 36 54 AM" src="https://user-images.githubusercontent.com/8104012/120122310-53d3fb80-c1a8-11eb-88ed-3e27322e309a.png">

**Comment by Anesti22** [comment]
Now that the issue with the height was fixed, another one came up which is the transition part, so i had to go to readmore.js make some changes, also the `.hidden` class is no longer needed because we we need the height to come form the outerHeight of the element.

1. 
.text-block__content {
	overflow: hidden;
	&.hidden {
		// height: auto!important;
	}
}

2. Added this -> `expandedHeight = expandedHeight - 60,` line!
```
var el = element.clone().css({
          height: 'auto',
          width: element.width(),
          maxHeight: 'none',
          overflow: 'hidden'
        }).insertAfter(element),
        expandedHeight = el.outerHeight(),
	expandedHeight = expandedHeight - 60,
        cssMaxHeight = parseInt(el.css({maxHeight: ''}).css('max-height').replace(/[^-\d\.]/g, ''), 10),
        defaultHeight = element.data('defaultHeight');

    el.remove();
```
