### ISSUE TITLE
Firefox measures wrong height

### ISSUE THREAD

**Issue by sPaCeMoNk3yIam** [jedfoster/Readmore.js#175]
I have a strange problem, I cannot reproduce in a js fiddle:
On Firefox some readmore elements tend to not show the full height when expanded. I debugged the readmore script and found the problem must have to do with the `.outerHeight()` calculation immediately after cloning the object and setting it to full height. When I debug into the code, the calculation goes fine, when I just have a console output it's 20px less than it should be. I cannot explain what's happening. Maybe the DOM-drawing isn't finished at the time `.outerHeight()` is called?
Any ideas?

**Comment by daigo-t** [comment]
I got a similar problem, too.
On Firefox for Mac, readmore.js does not get correct height when opening.

*See below:
http://ok-brand.com/2016/
(On the other browsers, it works well.)

Could anyone teach me how to solve?

**Comment by Fly06-Fr** [comment]
Same problem here too w/ Firefox.

Apart from that, it's a very nice ans easy plugin.

**Comment by jedfoster** [comment]
Version 3.0 of Readmore.js will drop jQuery entirely, in favor of vanilla JS. I believe this will be fixed in the next version.
