### ISSUE TITLE
Demo doesnt work with jquery-3.1.0

### ISSUE THREAD

**Issue by Chrysweel** [jedfoster/Readmore.js#183]
Hello.

I want use this library, but I have jquery-3.1.0 , and demo does not work. 

Are there some solution ? Or some pull request pending to accept and fix this error ?

Thanks in advance !

**Comment by UralZima** [comment]
I have same issue. overflow:hidden is not setting on the element, need to do it manually...

**Comment by CNK001** [comment]
Readmore selector doesn't  work on jQuery 3.1.1:

`<style> undefined + [data-readmore-toggle], undefined[data-readmore]{display: block; width: 100%;}undefined[data-readmore]{transition: height 100ms;overflow: hidden;}</style>`

**Comment by hiddebroerse** [comment]
`    $.fn.readmore = function(selector, options) {
        var args = arguments,
            selector = selector;`

I added the selector as argument for the plugin. It's not the most stylish solutions but it works fine.

**Comment by jedfoster** [comment]
Version 3.0 of Readmore.js will drop jQuery entirely, in favor of vanilla JS.
