### ISSUE TITLE
It does not work in chrome

### ISSUE THREAD

**Issue by streetcoder** [jedfoster/Readmore.js#185]
I have installed it properly and see it works nice in firefox but does work at all in chrome. Please could tell someone how can I fix it?

**Comment by dotanm** [comment]
First, try to open the demo that is received with the code, and see if that works. If it does not, then you have a much bigger problem.

If the demo works, then make sure that in your implementation you are using the <article> tag, and do not replace it with something else.

For me this was the reason the page did not work on Chrome.
