### ISSUE TITLE
Can't exclude jQuery when building with Browserify.  I would like to rely on existing jQuery global rather than packaging all of jQuery into the Readmore.js build.  Is there a way to do this?

### ISSUE THREAD

**Issue by alexington** [jedfoster/Readmore.js#190]
My site pulls jQuery from a CDN.  I package all other JS dependencies into a bundle using Browserify.  So my `<script>` tags look kind of like this:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="/static/bundle.js"></script>  <!-- Browserified bundle -->
<script src="/static/app.js"></script>
```

I'd like to include Readmore.js into the bundle with `require('readmore-js')`.

Normally, when a library has a jQuery dependency, I can exclude jQuery from the Browserify build like this, as described in [Browserify's docs](https://github.com/substack/browserify-handbook#excluding):

```
$ browserify src/main.js --exclude jquery -o js/bundle.js
```

When I try this with Readmore.js, the Browserify build is successful.  Readmore is included in the bundle, jQuery is not.

**But loading the page in the browser produces the following error:**
```
Uncaught Error: Cannot find module 'jquery'
    at readmore (readmore.js:20)
```
Here is failing portion from `readmore.js`:
```
(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD
    define(['jquery'], factory);
  } else if (typeof exports === 'object') {
    // CommonJS
    module.exports = factory(require('jquery'));       // <-- Line 20
  } else {
    // Browser globals
    factory(jQuery);
  }
}(function($) {
```

So I guess it thinks I'm attempting to do a CommonJS import of jQuery? I want to end up in the third `else` block and make use of the `jQuery` global instead.

I experimented by changing that portion of the `readmore.js` source to the following:
```
(function(factory) {
    // Browser globals
    factory(jQuery);
}(function($) {
```
And that produces the desired results.  I can build the bundle with Browserify, include Readmore, exclude jQuery, and Readmore will use the existing `jQuery` global.

**So, is there a proper way to do this with Readmore.js?  To bundle it with Browserify but exclude the jQuery dependency?**  I'm relatively new to using Browserify, so this could be a misunderstanding on my part.  However, I've been able to do this with other JS modules successfully.  Any advice and tips welcome, thanks a lot!

**Comment by jedfoster** [comment]
Version 3.0 of Readmore.js will drop jQuery entirely, in favor of vanilla JS.
