### ISSUE TITLE
expanded height of elements with padding will be too much

### ISSUE THREAD

**Issue by developpeur2000** [jedfoster/Readmore.js#191]
Issue seen on V2.2.0
In setBoxHeights, the element is cloned, including classes that may contain padding applied on it.
as you set the width of the clone using element.width(), the padding will be applied on top of this width, thus reducing the width and making the calculated height too big.
problem is solved by using element.innerHeight() instead

**Comment by hvanzandbrink** [comment]
I have the same issue. The solution given by @developpeur2000 is correct if you use element.innerWidth() instead of element.width()

**Comment by jedfoster** [comment]
Version 3.0 of Readmore.js will drop jQuery entirely, in favor of vanilla JS.
