### ISSUE TITLE
Concat Text with ...

### ISSUE THREAD

**Issue by dnicastro** [jedfoster/Readmore.js#192]
Nice Plugin, thanks for your work.

I've an idea for a feature:
What do you think about add some **...** when truncate the text?
I think, this would be a nice feature and UI-improvement.

Example
![bildschirmfoto 2017-02-21 um 11 30 37](https://cloud.githubusercontent.com/assets/8959959/23161197/7d371cac-f829-11e6-8a15-fe1df93f2353.png)

Best
Daniele

**Comment by sujiths7** [comment]
Is there any hack for this?

**Comment by jedfoster** [comment]
I'm sure there's some way to do this, but Readmore.js was not designed to do it. There are many other similar libraries that do offer this feature.
