### ISSUE TITLE
afterToggle not triggering

### ISSUE THREAD

**Issue by mabdullah2010** [jedfoster/Readmore.js#194]
This is not actually an issue with the code, but the documentation could be explicit about this pitfall:

If speed is set to 0, afterToggle does not trigger because there no transitionend event gets generated.

I spent a long time trying to figure out why afterToggle was not being triggered, and the reason makes sense. I just wanted to document this somewhere in case someone else encountered the same problem.

**Comment by roballport** [comment]
@mabdullah2010 You just saved my sanity! Thanks  :)
