### ISSUE TITLE
Text still visible before toggle

### ISSUE THREAD

**Issue by unrealxqt** [jedfoster/Readmore.js#196]
Hi,

By default the text should be hidden until I click read more but it is still visible by default and goes off the screen and looks terrible. The read more link only enlarges the container itself but does not touch the text.

Please find the files I use in the attachments.

ps.: Tried to upload the files I use in ZIP format but github states "We don't support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF or ZIP." :\

**Comment by unrealxqt** [comment]
I managed to attach 2 screenshots of the issue.

![readmore_1](https://cloud.githubusercontent.com/assets/20015173/24836966/7384ff42-1d29-11e7-9497-5571d17b2f3a.jpg)
![readmore_2](https://cloud.githubusercontent.com/assets/20015173/24836967/73a38804-1d29-11e7-9010-277525f1be7a.jpg)

**Comment by unrealxqt** [comment]
Not sure if this helps, but also managed to upload my files in txt format.

main.txt is main.css in the css folder
models.txt is models.html in the root folder
responsive.txt is responsive.css in the css folder.

plus your readmore.min.js in the js folder
[main.txt](https://github.com/jedfoster/Readmore.js/files/908162/main.txt)
[models.txt](https://github.com/jedfoster/Readmore.js/files/908164/models.txt)
[responsive.txt](https://github.com/jedfoster/Readmore.js/files/908163/responsive.txt)

**Comment by unrealxqt** [comment]
managed to fix the problem by adding this line to main.css

article {
overflow: hidden;
}

**Comment by rtpHarry** [comment]
I'm seeing this issue as well, with v2. The readme says that it uses overflow hidden to manage the process but it doesn't seem to be injecting it.
