### ISSUE TITLE
Not working with image

### ISSUE THREAD

**Issue by ashish19902002** [jedfoster/Readmore.js#200]
Readmore js is not working properly with an image only. Can any please suggest any solution.

**Comment by onetrev** [comment]
I am finding it's not working properly with an image AND content. I have a block with an image in the hidden section and when expanded the section height is still not tall enough, it looks like possibly the height of the image is not being factored in.

**Comment by onetrev** [comment]
I discovered what is causing this bug -- for me at least. If you have an image using `srcset` then the height of it is NOT calculated. Using the same image, same setup exactly, but without srcset and it works perfectly.

**Comment by onetrev** [comment]
Was this issue fixed, as `srcset` is only becoming more and more standard practice?
