### ISSUE TITLE
Not working with Internet Explorer

### ISSUE THREAD

**Issue by tomcatooo** [jedfoster/Readmore.js#204]
I have this plugin working fine with Chrome and Firefox, any idea how to make it function with IE?

Thanks

**Comment by sebastianschmid** [comment]
Can you please supply a non-working minimal example, preferrably in codepen.io? And don't forget to add your version of Internet Explorer :)

**Comment by NT100** [comment]
I have the same problem.  It works fine in Microsoft Edge, Chrome but not IE 11 no matter it's in Windows 7 64-bit or Window 10 64-bit.

I've enabled Script sessions but still have the same problems
