### ISSUE TITLE
back to top anchor

### ISSUE THREAD

**Issue by BlueWolf-Produktion** [jedfoster/Readmore.js#208]
i'll try to set a "back to top" anchor for closing big text elements. It's not working.
Maybe an option for the next release?

`lessLink: '<a href="#readmore-jumpback">`

**Comment by sebastianschmid** [comment]
Where exactly would you like to have this? Testing it at the demo page http://jedfoster.com/Readmore.js/, no matter what I do, I always end up seeing the original headline on my screen.

To make it smooth and avoid jumping, and therefore confusing your visitor, I suggest using $('html, body').animate(scrollTop, [positionInPixels]) as a callback, wouldn't that work?

**Comment by BlueWolf-Produktion** [comment]
Just look here: https://www.natursteinpflege24.de/steinschutz/guter-schutz-vermeidet-flecken-und-erleichtert-die-reinigung
It´s a very lang text. After closing it, you´ll see only the footer of the page.

**Comment by Puy-Robin** [comment]
Can you say how you solved this as I'm having the same problem.
