### ISSUE TITLE
Set the number of words ?

### ISSUE THREAD

**Issue by vince83110** [jedfoster/Readmore.js#210]
Maybe I am stupid, but how to set the number of words / letters to show before "read more" button ? Thanks.

Ok stupid plugin really... Only set by height, even if you don't have text it will the show "read more" button. Hope you didn't spend much time on it.

**Comment by jasterba** [comment]
This might be what you're looking for.
https://github.com/amazingSurge/jquery-shorten

**Comment by jedfoster** [comment]
Readmore.js was not designed to function on individual words.
