### ISSUE TITLE
Version 2.2.0 isn't available in yarnpkg repository

### ISSUE THREAD

**Issue by yarieldis** [jedfoster/Readmore.js#213]
yarn add readmore-js will install version 2.1.0.

**Comment by yarieldis** [comment]
Neither in npm repository.

**Comment by garygreen** [comment]
@jedfoster bump any news? Looks like you forgot to npm publish.... ?

**Comment by jedfoster** [comment]
2.2.1 is now on npm. https://www.npmjs.com/package/readmore-js
