### ISSUE TITLE
Collapsed lines

### ISSUE THREAD

**Issue by eparama** [jedfoster/Readmore.js#214]
Hi Jed, thanks for this great feature, I am using it now in most of my pages. I just have a question regarding how I want to show the readmore button only when the texts exceed 3 lines(instead of collapsedHeight), then show the read more link. Otherwise don't show it.  Can your code already handle this, I am just curious.

**Comment by jedfoster** [comment]
No, the current version of Readmore.js does not accept number of lines, only height. But you could achieve the same effect with a `collapsedHeight` equal to the desired number of lines, multiplied by the line height. (e.g. assuming 16px font with line-height of 1.5, `collapsedHeight: 72` would show the first three lines of text in a block. `16 * 1.5 * 3 = 72`)
