### ISSUE TITLE
Call Back and Speed Option is not working 

### ISSUE THREAD

**Issue by sumitkalia** [jedfoster/Readmore.js#215]
Hi, I am using jquery 3.2.1 and bootstrap 4

I have tried 

$('article').readmore({
  speed: 75,
  lessLink: '<a href="#">Read less</a>'
});

but speed is not affecting at all.

**Comment by pashkes** [comment]
@sumitkalia You need will add css property transition for a text block

**Comment by sumitkalia** [comment]
Thank @pashkes

Solution: 

.article{
transition: all 0.5s;
}
