### ISSUE TITLE
Breaks with newer versions of jquery

### ISSUE THREAD

**Issue by jennnjennjen** [jedfoster/Readmore.js#216]
If you replace in the demo the line where it links to jquery with a newer version (<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>), you'll see it no longer works properly. 

Used this script for years though and really liked the ease of use. Thanks! Hope it gets updated at some point!

**Comment by StirStudios** [comment]
Apply the patch or update manually and all will work again:
https://github.com/jedfoster/Readmore.js/pull/206

**Comment by jedfoster** [comment]
Version 3.0 of Readmore.js will drop jQuery entirely, in favor of vanilla JS.
