### ISSUE TITLE
Can't initiate readmore with an element

### ISSUE THREAD

**Issue by Dahkon** [jedfoster/Readmore.js#227]
Hello,
This example on the documentation page is not working :
`new Readmore(selector String | Element | NodeList);`

I'm trying to pass an element as the constructor but element can't be used with queryselectorall.

My test code : 
```
            $('.readmore').each(function() {
                var n=$(this).data('count');
                new Readmore($(this)[0], {
                    collapsedHeight: 0,
                    moreLink: '<a href="#"><strong>Voir les ' + n + ' réponses</strong></a>',
                    lessLink: '<a href="#"><strong>Replier</strong></a>'
                });
            });
```

**Comment by fabiosangregorio** [comment]
+1

**Comment by jedfoster** [comment]
I believe the latest alpha version fixes this issue. https://www.npmjs.com/package/readmore-js/v/3.0.0-alpha-4

I'm going to close this for now, but feel free to reopen if you still have trouble after updating.
