### ISSUE TITLE
moreLink and lessLink don't accect html inside A tag

### ISSUE THREAD

**Issue by Dahkon** [jedfoster/Readmore.js#228]
Hello,

You're using parentNode in your code so we can't use html inside A tag in more and less links html.
```
                moreLink: '<a href="#"><strong>More</strong></a>',
                lessLink: '<a href="#"><strong>Less</strong></a>',
```

It's not working because of the strong tag. A link tag is created inside the A tag after each click on the link. You can see the result easily while inspecting generated code.

**Comment by jedfoster** [comment]
Fixed in #224
