### ISSUE TITLE
Version 2 doesn't work

### ISSUE THREAD

**Issue by mikemix** [jedfoster/Readmore.js#229]
@jedfoster example: https://jsfiddle.net/0679fux2/3/
At least in latest stable Firefox. Looks like the `overflow: hidden` is missing.

Previous version `1.0.0` works well.

**Comment by soundslocke** [comment]
Interestingly it seems to still work when used with versions of jQuery prior to 3.x. I didn't trace down what jQuery change causes the break but adding the appropriate `overflow` property in readmore.js fixes this. See [our fork](https://github.com/GigSalad/Readmore.js).

I didn't try it out but the [upcoming new version of readmore](https://github.com/jedfoster/Readmore.js/tree/version-3.0) might work fine and not have this problem?

**Comment by jedfoster** [comment]
Something changed in jQuery 3. Not sure what, but I'm dropping support for jQuery altogether. I haven't used it on a project in nearly five years. Readmore.js v3 should fix a lot of the jQuery-related issues that have come up.
