### ISSUE TITLE
Making sure other divs are collapsed before opening the readmore

### ISSUE THREAD

**Issue by tkakar** [jedfoster/Readmore.js#230]

**Comment by tkakar** [comment]
I have a bunch of similar divs on a page with each one having a readmore link. How can I make sure that no other div is open before expanding one.

Any help would be appreciated!

**Comment by tkakar** [comment]
Solved!

**Comment by alexhooley** [comment]
> 
> 
> Solved!

Looking for this as well. Any info on how you did it?
