### ISSUE TITLE
Uncaught ReferenceError: __VERSION__ is not defined

### ISSUE THREAD

**Issue by Pupinia** [jedfoster/Readmore.js#232]
Hi, i use 3 version, and then a import and use library - 
```
import Readmore from 'readmore-js';
new Readmore('target');
```
i have error -
`readmore.es6.js:397 Uncaught ReferenceError: __VERSION__ is not defined at Module../node_modules/readmore-js/dist/readmore.es6.js`
If i comment ```Readmore.VERSION = __VERSION__; ``` all work fine. 
node version - v11.11.0.

**Comment by Luckyfella73** [comment]
Yes, looks like `__VERSION__` has to be defined first. Like @Pupinia said commenting out helps for a start

**Comment by jedfoster** [comment]
Ahh. I fixed this, but it's in a different branch. I'll work on getting it into the main version 3 branch and cut a new release.

**Comment by jedfoster** [comment]
This should be fixed now. 
```
$ npm install readmore-js@next
```
