### ISSUE TITLE
v3.0.0-1 (beta) wont work with webpack + using 'new Readmore('...')

### ISSUE THREAD

**Issue by Chrisser73** [jedfoster/Readmore.js#237]
I tried to update from 2.2.1 to 3.0x because of the unsolved issue:
https://github.com/jedfoster/Readmore.js/issues/233

I've installed it like the description said:
https://github.com/jedfoster/Readmore.js/tree/version-3.0

What I've recognized was, that there is no ./src/.. folder after the install, only a /dist-Folder wehre the readmore.js is inside but the Readmore.js sais:
`__webpack_require__(/*! ./src/readmore.js */"./src/readmore.js");`
??

Then i used:
`require('readmore-js');`
also like in the description... (even though the folder structure is now different then in 2.2.1)

Anyway followed the instruction when i have to use:
`new Readmore('article');`
but it wont work, because it could not find "Readmore", because its not there, because it could not include readmore.js because of the missing src folder.

Even if i try to insert the src folder manually, trying to use new Readmore() in any different and possible way or something else it wont work!

For me, V3 is broken or tell me whats wrong pls.
Thank you

**Comment by pammel** [comment]
This way it worked for me with webpack (3.0.0-beta-1):

```
const Readmore = require('readmore-js');
global.Readmore = Readmore;
```

Then you have to call it with:
```
new Readmore.default('article');
```

**Comment by jedfoster** [comment]
Good catch. That's bug in the documentation. 

Should be more like what @pammel showed: 

```javascript
const Readmore = require('readmore-js');

new Readmore('article');
```

**Comment by Chrisser73** [comment]
thank you, an there where also missing type definitions for typescript in my project :s

**Comment by decadence** [comment]
Works for me like this:

```javascript
const Readmore = require('readmore-js').default;

// or
import Readmore from 'readmore-js';

// call
new Readmore('article');
```
