### ISSUE TITLE
With jquery-3.1.1 animation not working

### ISSUE THREAD

**Issue by arulprasadj** [jedfoster/Readmore.js#238]
Hai 
with jquery-3.1.1.min.js animation (transition style is not adding  automatically) text also over laping

**Comment by zdimaz** [comment]
Yeach !
Die plugins function (options) in new version JQ

**Comment by zdimaz** [comment]
Animation (get element and scroll top), and speed not work !

**Comment by harryfear** [comment]
Same issue in 2021.

**Comment by DanielYorwarth** [comment]
Still having this issue

**Comment by jedfoster** [comment]
jQuery 3 is not supported. Probably won't be. I haven't used any version of jQuery in years.
