### ISSUE TITLE
Any way to use this on content that's injected into the dom using JavaScript?

### ISSUE THREAD

**Issue by ygagnon** [jedfoster/Readmore.js#250]
I'm trying to implement this on job descriptions that are retrieved from the workable.com API and injected into the DOM dynamically.  I thought that I could get it to work by simply wrapping jQuery's "$( document ).ready(function() {}" around it .. but no cigar.  I'm not getting any JavaScript errors or anything, .. and I was able to get everything to work properly when I hardcoded the content into the page (the readmore toggles then work).  But otherwise, I just can't seem to get it to work with the dynamically injected content.  

Here's the page where I've been trying to implement it one (my JS code is at the every bottom of the page if you view source):

https://www.workforlgihomes.com/job-openings.html

So what's the trick?  Or is just not possible to achieve this?  

Thanks,
-- Yvan

**Comment by ygagnon** [comment]
It's now been 4 days and I still haven't gotten any kind of response.  Is this JS library no longer being maintained or supported?

Here is the updated link:  https://www.workforlgihomes.com/job-openings_NEW.html

Thanks,
-- Yvan

**Comment by jedfoster** [comment]
Check out the Ajax demo: https://github.com/jedfoster/Readmore.js/blob/master/ajax-demo.html
