### ISSUE TITLE
Is there away to change the read more/less button tag

### ISSUE THREAD

**Issue by noderole** [jedfoster/Readmore.js#252]
hi,
is there a way to change this:
`<a href="#" data-readmore-toggle="footer__aboutParagraph"  aria-controls="footer__aboutParagraph">Read More</a>
`
to this:
`<a href="#" data-readmore-toggle="footer__aboutParagraph"  aria-controls="footer__aboutParagraph" class="">Read More</a>
`
Thank you

**Comment by jedfoster** [comment]
You want to add an empty `class` attribute? Why?
