### ISSUE TITLE
Text doesn't fulle expanded if contain video or(sometimes) images

### ISSUE THREAD

**Issue by Freika** [jedfoster/Readmore.js#39]
I totally love your script and using it here: http://delicatr.ru/
But sometimes there is a problem with expanding posts, which contains one or more video from youtube (i think, bug will appear with every iframe tag) or (not every time) images. How can I repair this thing?

Thanks in advance.

**Comment by jedfoster** [comment]
I believe that this issue and #51 have similar root causes. I'm working on a 2.0 version that will call to init() inside a window load event callback, which should solve these issues.

**Comment by simongoot** [comment]
Still having this issue in chrome for iOS

**Comment by onetrev** [comment]
Same here, works fine until I include an image. And even if I fire the script in a window.onload function, no luck. I believe this issue and https://github.com/jedfoster/Readmore.js/issues/200 are reporting the same thing.
