### ISSUE TITLE
Is there a way to create an AngularJS directive?

### ISSUE THREAD

**Issue by exislow** [jedfoster/Readmore.js#41]
I want to use Readmore.js with AngularJS. It works partially only with the initial/default values. I can't pass options.

I've tried it with Angular-UI jQuery Passthrough (http://angular-ui.github.io/ui-utils/#/jq) 

```html
<div id="disclaimer" ui-jq="readmore">
[...]
```
```js
.value('uiJqConfig', {
		// The jQuery Plugin namespace
		readmore: {
			// Readmore options. This object will be used as the defaults
			speed: 1000,
			embedCSS: false,
			moreLink: '<div class="horizontal-line"><span class="line-center arrow-down">Kompletten Disclaimer anzeigen</span></div>',
			lessLink: '<div class="horizontal-line"><span class="line-center arrow-up">Disclaimer schließen</span></div>'
		}
	})
```
But only the default values are applied ('Read more', 'Close').

And I also developed a directive by myself:
```html
<div id="disclaimer" bs-readmore>
[...]
```
```js
.directive('bsReadmore', ['$log',
			function ($log) {
		return {
			link: function (scope, element, attrs) {
				//$log.log(scope, element, attrs);
				$(element).readmore({
					speed: 1000,
					embedCSS: false,
					moreLink: '<div class="horizontal-line"><span class="line-center arrow-down">Kompletten Disclaimer anzeigen</span></div>',
					lessLink: '<div class="horizontal-line"><span class="line-center arrow-up">Disclaimer schließen</span></div>'
				});
			}
		};
	}])
```

Same behavior as before. My Options won't be applied.

Is there some magic, which I didn't see?

**Comment by Aerlinger** [comment]
I agree, this would be a good candidate for an Angular directive.

**Comment by jedfoster** [comment]
Coming soon...

**Comment by jedfoster** [comment]
Would someone care to comment on this? 

http://jsbin.com/serupu/3/edit?html,js,output

As you can see, config options can be set as attributes of the directive element. The drawback I see to this is that a full jQuery is required—Angular's jqLite is not sufficient—meaning an additional dependency.

@exislow @Aerlinger @kburns1

**Comment by TheoKouzelis** [comment]
@jedfoster that example worked great for me with static text but when I started using angular variables to fill my articles I had to add a $timeout to the directive to get it to get it to work. Not sure exactly why, but it worked for me :)
```
module.directive('readmore', ['$timeout', function($timeout) {
        return {
            restrict: 'CA',
            link: function(scope, element, attributes) {
                $timeout(function(){
                    angular.element(element).readmore(attributes);
                });
            }
        };  
    }]);
```
http://stackoverflow.com/questions/12240639/how-can-i-run-a-directive-after-the-dom-has-finished-rendering

**Comment by jedfoster** [comment]
I think the better approach would be a complete rewrite as a proper Angular directive.
