### ISSUE TITLE
Text being cut off.

### ISSUE THREAD

**Issue by i7nvd** [jedfoster/Readmore.js#51]
![image](https://cloud.githubusercontent.com/assets/2649000/3379694/fff215ee-fbf5-11e3-9847-510bf40fb975.png)

I can't figure out why, but in the expanded view on one section, the text is cut off. If I resize to a smaller screen dimension, this one is fixed as you can see here: 

![image](https://cloud.githubusercontent.com/assets/2649000/3379709/45ec57d0-fbf6-11e3-867e-888d99db2898.png)

however, it breaks another one that was working at full size. Can you help me figure out why this is?

![image](https://cloud.githubusercontent.com/assets/2649000/3379713/5f91d99e-fbf6-11e3-802f-2ba580b56d46.png)

**Comment by jedfoster** [comment]
I'm working on a 2.0 version of this plugin. One of the changes is to wrap the call to `init()` in a window `load` event listener, thereby allowing layout-affecting content such as images to load so their height can be included in the calculations Readmore.js performs. This is similar to the solution proposed in #57, but avoids an additional round of repainting.

This _should_ (??) finally solve this problem.

**Comment by JayHoltslander** [comment]
Hmm if this was fixed in 2.0 how come I'm having this issue and Googling a fix led me here? 😒

**Comment by Chillifish** [comment]
Still having the problem and can't find a way round it. Seems to be related to jQuery outerHeight() giving the wrong size. The v3 alpha version doesn't rely on jQuery and seems to have fixed the issue.
