### ISSUE TITLE
Hiding Images in the Readmore Div

### ISSUE THREAD

**Issue by ndura1** [jedfoster/Readmore.js#56]
Hi everyone,

Currently building a website using Foundation 5. I have tried a ton of expander, truncate, and read more plugins. None of them play nice with Foundation. Some remove line heights, others break accordions and tabs. Readmore.js is the only one that doesn't break all the functionality. My question is that I have some divs that have images floating in them and when the text is collapsed, you can see the top of the image. Is there a setting or a workaround to keep the images hidden until the readmore div is expanded.

Any help would be appreciated tremendously!

**Comment by DivaVocals** [comment]
The posted solution doesn't work.. is there a solution for hiding images when the content is collapsed and only displaying them when the "Read More: link is clicked??

http://tlwtestsite(dot)tablelegworld(dot)com/Table-Height-Table-Legs
