### ISSUE TITLE
Readmore.js Hight Issue

### ISSUE THREAD

**Issue by bricealef** [jedfoster/Readmore.js#61]
Hey Jed. I've successfully installed readmore.js on my site page but there appears to be a bug where the section i've assigned for expansion only expands part way, leaving the rest of the text hidden. I'm not sure what I did wrong. Please help.
![screen shot 2014-10-08 at 12 31 20 pm](https://cloud.githubusercontent.com/assets/3988044/4565714/64c46376-4f22-11e4-92b8-d6fdb132a0d0.png)

**Comment by jedfoster** [comment]
@bricealef I suspect that images for your social media links are throwing off Readmore's calculations; its calculating the height of that section before the images have loaded. I believe that this issue and #51 have similar root causes. I'm working on a 2.0 version that will call `init()` inside a window load event callback, which should solve these issues.

@vdsabev I took a look at your link, and I'm not seeing the issue you describe, were you able to find a solution?

**Comment by vdsabev** [comment]
@jedfoster we worked around the issue by adding some extra padding to the bottom of the expanded section. Now that I think about it, it makes sense that the social media buttons at the bottom were the culprit. Hopefully your fix will solve the problem permanently, I'll let you know if there are any further issues. Thanks!
