### ISSUE TITLE
readmore.js doesn't work with content that is added dynamically

### ISSUE THREAD

**Issue by pafcu** [jedfoster/Readmore.js#76]
readmore.js waits for the 'load' event of window to trigger before initializing. However, this means that it's not possible to add readmore to content which is added after the page load (by javascript). Maybe add an option to not wait for the load event? Or maybe add an option to listen to some user-specified event instead.

**Comment by ziazek** [comment]
Faced this issue as well; it doesn't work for Rails Turbolinks. 

I added lines 165-167 of https://gist.github.com/ziazek/c2012fc48f441db63656 to make it work.

**Comment by travismeyer** [comment]
This seems to affect embedded code from Youtube as well, but only in Safari, not Chrome.

**Comment by erikcvisser** [comment]
Zlazek's fix verified.

**Comment by taqmaninw** [comment]
Thank it's work from chrome

**Comment by jedfoster** [comment]
v2.0.2 should fix this.
