### ISSUE TITLE
Ignoring CSS max-height

### ISSUE THREAD

**Issue by amosgroth** [jedfoster/Readmore.js#77]
Hi there,

I'm trying to use readmore.js with a div and the CSS max-height property as follows:

.category-description { margin:0 0 10px; max-height: 100px; }

jQuery(document).ready(function(){

	if(jQuery('.category-description')) {
		jQuery('.category-description').readmore({
			speed: 400,
			moreLink: '<a href="#">>> weiterlesen</a>',
			lessLink: '<a href="#"><< weniger</a>'
		});
	}
}

But it doesn't work because readmore.js ignores/overwrites the max-height CSS setting and uses the standard 200px:

<div class="category-description std" style="max-height: none; height: 200px;" data-readmore="" aria-expanded="false" id="rmjs-1">...TEXT...</div>

Do you have any suggestions?

Thanks
Amos

**Comment by mla** [comment]
Hey @amosgroth, any luck with this? I'm experiencing the same thing.

I'm using Readmore.js with Foundation 5.

**Comment by sfavot** [comment]
Same problem here.

**Comment by mla** [comment]
Yeah, I tried the latest version again last week and still couldn't get the CSS max-height to work.
Would be awesome if someone has an actual example of it working?

**Comment by jedfoster** [comment]
@sfavot @mla Could you please post examples of it not working?

**Comment by mla** [comment]
I tried to get an example working on jsfiddle, but there's something wrong with it. Here it is, for reference:
http://jsfiddle.net/2t73h23v/12/

Here's a gist of the full HTML based on your demo.html:
https://gist.github.com/mla/c467611a1b684ff17610

No matter what I set max-height to, it seems to be ignored.

**Comment by jedfoster** [comment]
Couple issues with your fiddle: 

1) I wouldn't try to use `max-height` directly on an element with a `style` attribute, at least not with Readmore.js. I moved that declaration to the CSS. 
3) The init'ing JavaScript needs to appear either at the end of the `<body>` or run on DOM ready, not just on load.

Here's your example with working `max-height`: http://jsfiddle.net/2t73h23v/14/

If the inline styling is truly important, then Readmore.js will need to be fixed so it doesn't stomp on existing `style` attributes. Not sure how difficult that would be. But I would _strongly_ recommend against inline styles.

**Comment by mla** [comment]
Excellent! Thanks :)

Yeah, I was just using inline to test it. I didn't realize it would affect the result.

**Comment by d8v15** [comment]
Um Your answer has nothing to do with foundation which was the original question
