### ISSUE TITLE
Does not always work correcly on webkit-based browsers

### ISSUE THREAD

**Issue by pafcu** [jedfoster/Readmore.js#78]
in setBoxHeights a copy of a element is made, inserted into the DOM, and then the height is calculated. This sometimes fails on webkit-based browsers, because insertAfter may return before the DOM has actually been updated, which results in an incorrect height calculation. Thus, reaqdmore.js only works with very simple content using webkit, when the insertion is fast enough that it has finished before the call to el.outerHeight().

**Comment by jedfoster** [comment]
Can you post a Gist with an example of this? I am unable to reproduce.

**Comment by stargOOse** [comment]
Have the same issue on Safari 8.0.6 Wrong height of element is calculated. Looks like the images could cause the problem.
Example: http://mobilitaet2050.vcd.org/community/unterwegs/nichtohnemeinfahrrad/
Second element "Georg - Dein Transportrad für Bocholt" 
expandedHeight in safari: 887px
expandedHeight in chrome: 1989px (correct)

**Comment by pmeissner** [comment]
Yes. Images are making the calculations too low. I tried using imagesLoaded.js to see if that would help the calculations, but no joy.
