### ISSUE TITLE
Doesn't work on classes

### ISSUE THREAD

**Issue by souinhua** [jedfoster/Readmore.js#83]
$(".class_name").readmore({
            maxHeight: 100
 });

The last item on that class name will not have readmore

**Comment by jedfoster** [comment]
Need more information. Can you post the code for page as Gist?

**Comment by EnMod** [comment]
Same here, it seems to work on classes sometimes, not all.

**Comment by jedfoster** [comment]
Need more information. Can you post the code for page as Gist?

**Comment by EnMod** [comment]
https://gist.github.com/EnMod/9a983b66a8e66b81aee3

**Comment by jedfoster** [comment]
Works for me: http://jsbin.com/kuqaxa/2/edit?html,css,js,output

**Comment by EnMod** [comment]
huh...turns out that it doesn't work on divs with initial display of none. Well that's my blunder since I didn't realize my current JS behavior and config was interfering.  Thanks!
