### ISSUE TITLE
Append symbol at the end of truncated text

### ISSUE THREAD

**Issue by leecollings** [jedfoster/Readmore.js#89]
Is it possible to add a symbol, or content at the end of the article text when in truncated mode?

So the end of the text would end like... and then show the readmore link?

**Comment by jedfoster** [comment]
This would be my recommended solution to your request: http://jsbin.com/higede/1/edit?html,js,output

Note that it's important that your `moreLink` (and `lessLink`) be a single element; it's OK for it to have children, but it needs to be a single outer element. So this will _not_ work: `<span>...</span><a>More</a>`.

**Comment by DivaVocals** [comment]
In case anyone like me comes here looking for a similar solution, I wanted to say thanks for this and to share a slight variation on the posted solution which worked better for me:

`moreLink: '<div>[...]<br /><br /><a href="#">Read more...</a></div>'`

http://tlwtestsite(dot)tablelegworld(dot)com/Motorized-Table-Legs

**Comment by leecollings** [comment]
Maybe this could be applied as a future feature enhancement, as it would make a lot of sense to be able to display text in this way, as it's more commonly seen like this when showing excerpts of text with 'Read More' links?
