### ISSUE TITLE
Add an option to hide the trigger when text is <= than collapsed height

### ISSUE THREAD

**Issue by idflood** [jedfoster/Readmore.js#90]
Hi,

It would be great to add this option. I've made the necessary changes on a local copy and I would like to make a pull request. But before that, I think it's best to discuss how it should be added.

- First option would be to make it optional and simply use the `show()` and `hide()` jquery methods.
- The second idea is to simply add classes to the the trigger element, like `readmore--hidden` for instance.

I think the second option is nicer since it is more flexible and doesn't add another option to the plugin. What do you think?

**Comment by jedfoster** [comment]
This should already be the default behavior. As demonstrated in [demo.html](https://github.com/jedfoster/Readmore.js/blob/master/demo.html), if a section's height is less than the configured `collapsedHeight` (or CSS `max-height`), the trigger is not shown.

I'd like to see an example of the behavior you are trying to address. Could you please post as a gist or fork [this bin](http://jsbin.com/kuqaxa/1/edit?html,js,output)?
