### ISSUE TITLE
Issue with using the readmore.js with rows of divs in bootstrap

### ISSUE THREAD

**Issue by thesteviep** [jedfoster/Readmore.js#91]
I am using bootstrap and have a row with multiple div blocks. I want to use the readmore.js functionality for this section.

I try to surround the content I want with the article tags but it is not working. I amusing the tag on other text and it works like a charm. 

I can send you a link to give you more information if you would like.

**Comment by jedfoster** [comment]
A link to code would be most helpful.

**Comment by thesteviep** [comment]
Mobilecause.me. Click the fundraiser and the impact tab

**Comment by jedfoster** [comment]
"Impact" tab looks fine, but I don't see what you are trying to do on the "Fundraisers" tab; what content are you trying to Readmore-ify and how are you marking it up?

**Comment by thesteviep** [comment]
I was putting the article tags around the doc content like I did with the
impact tab.

However it did not work with the fundraiser tab.

**Comment by thesteviep** [comment]
You want me to put the article tags on there. I left them out since they
weren't working.

**Comment by thesteviep** [comment]
I added the article tags to the tab
