### ISSUE TITLE
Displays jumps when collapsing content..

### ISSUE THREAD

**Issue by DivaVocals** [jedfoster/Readmore.js#92]
Can't seem to find this previously reported anywhere. But the display jumps when collapsing the content. It's bringing you to the top of the div container. I noticed this is also happening in the demo on the Readmore site too.. http://jedfoster.com/Readmore.js/

Is there a way to make the display just gracefully collapse without jumping.

http://tlwtestsite(dot)tablelegworld(dot)com/Table-Height-Table-Legs

**Comment by jedfoster** [comment]
The page "jumps" because you are animating a page scroll in your `afterToggle` callback:

```
    $('#category-collapse').readmore({
      //moreLink: '<div><div>[...]<br /></div><a href="#">Read more...</a></div>',
      moreLink: '<div>[...]<br /><br /><a href="#">Read more...</a></div>',
      lessLink: '<a href="#">Less...</a>',
      speed: 500,
      collapsedHeight: 75,
      heightMargin: 16,
      afterToggle: function(trigger, element, expanded) {
        if(! expanded) { // The "Less" link was clicked
          $('html, body').animate({scrollTop: $(element).offset().top}, {duration: 100});
        }
      }
    });
```
