### ISSUE TITLE
Using readmore.js adds # to end of URL

### ISSUE THREAD

**Issue by somimi** [jedfoster/Readmore.js#93]
When clicking on the Read More link, a pound character becomes appended to the site URL. It is a minor annoyance, but it does require clicking "back" twice in a browser to go to the previous page.

**Comment by paulAxonGarside** [comment]
Have you tried changing the default links in the setup?
```javascript
$('.read-more').readmore({
    moreLink: '<a class="readmore" href="javascript:;">Read more</a>',
    lessLink: '<a class="readmore" href="javascript:;">Read less</a>'
});
```
