### ISSUE TITLE
Race condition (expanding and collapsing again)

### ISSUE THREAD

**Issue by Ghostavio** [jedfoster/Readmore.js#95]
Hello, you have a race condition on this line: https://github.com/jedfoster/Readmore.js/blob/master/readmore.js#L155

Steps to reproduce: click on the Read More button as soon as it shows up (maybe wait for 1s and then click it), it will expand and then collapse again, displaying the Close button, as this line won't have finish executing by the time you click the button. Note that this is hard to reproduce, as it depends on how many scripts you have on your page and where the button is located. In my case, the button holds the main content of the page (the description), and it's possible to click it right after the page load. In the examples in your website, the buttons are in the very end of the page, making it hard to reproduce.
Maybe this should happen in a callback of the `init`method, because the current implementation can cause unwanted behaviours. I hotfixed it by commenting the line out (and the IE8 one as well) and adding the collapsed height of the element to the css (also avoiding FOUC, as on load the whole element is visible and then it collapses, confusing the user).

If you want, I can create a codepen trying to demonstrate the issue, and work on a pull request to fix it.

**Comment by jedfoster** [comment]
Could you please fork [this bin](http://jsbin.com/kuqaxa/1/edit?html,js,output) with your example?

**Comment by Ghostavio** [comment]
Hey, sorry I couldn't look into this for a while, I'll try it later today :)
