### ISSUE TITLE
is blocking another javascript

### ISSUE THREAD

**Issue by joloshop** [jedfoster/Readmore.js#97]
The script is interrupting with another javascript and blocking it from working, any solution??

**Comment by jedfoster** [comment]
Link to your page? It's impossible to diagnose an issue like this without seeing it. What do you mean by "blocking"?

**Comment by joloshop** [comment]
found the problem, there was a another script and it interfered with 
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
got it sorted out....
