### ISSUE TITLE
height by script if shorter

### ISSUE THREAD

**Issue by marcnetic** [jedfoster/Readmore.js#99]
Hello,
if an element has shorter content than the max-height, the element get a height by the script (i think it is the maxheight), so that there is to much space.
In version 2.0.1. the script does what i expect: if the content is less or shorter than the max-height the element get the height by its content (auto).

Can you fix it or do i something wrong?

**Comment by jedfoster** [comment]
If version 2.0.1+ does what you expect, just use that version.
